import type { Order } from "@/types/domain";

export function buildSamplePrintOrder(): Order {
  const now = new Date().toISOString();

  return {
    id: "00000000-0000-4000-8000-00000000test",
    order_number: 999,
    table_id: "00000000-0000-4000-8000-000000000012",
    service_id: null,
    order_type: "dine_in",
    takeaway_name: null,
    takeaway_pickup_at: null,
    status: "confirmed",
    cover_count: 4,
    cover_price_snapshot: 1.9,
    subtotal: 73.2,
    cover_total: 7.6,
    total: 80.8,
    general_notes: "Prova stampa admin",
    version: 1,
    created_by: "00000000-0000-4000-8000-000000000001",
    updated_by: "00000000-0000-4000-8000-000000000001",
    created_at: now,
    updated_at: now,
    sent_to_cashier_at: now,
    closed_at: null,
    table: {
      id: "00000000-0000-4000-8000-000000000012",
      table_number: 12,
      display_name: "Sala",
      active: true,
    },
    waiter: {
      id: "00000000-0000-4000-8000-000000000001",
      full_name: "Admin",
    },
    items: [
      {
        id: "test-pinsa",
        order_id: "00000000-0000-4000-8000-00000000test",
        menu_item_id: "pinsa-diavola",
        item_name_snapshot: "Diavola",
        item_price_snapshot: 9,
        ingredients_snapshot: null,
        quantity: 2,
        line_total: 18,
        notes: "ben cotta",
        preparation_area_snapshot: "pizzeria",
        version: 1,
        category_name: "Pinse rosse",
        category_slug: "rosse",
        category_sort_order: 2,
        extras: [
          {
            id: "test-extra-mozzarella",
            order_item_id: "test-pinsa",
            extra_name_snapshot: "Mozzarella",
            extra_price_snapshot: 1.5,
            quantity: 1,
            total: 1.5,
          },
        ],
      },
      {
        id: "test-ayce",
        order_id: "00000000-0000-4000-8000-00000000test",
        menu_item_id: "ayce-adulti",
        item_name_snapshot: "All You Can Eat · Adulti",
        item_price_snapshot: 16.9,
        ingredients_snapshot: null,
        quantity: 6,
        line_total: 101.4,
        notes: "",
        preparation_area_snapshot: "pizzeria",
        version: 1,
        category_name: "Formula All You Can Eat",
        category_slug: "all-you-can-eat",
        category_sort_order: 4,
        extras: [],
      },
      {
        id: "test-cucina",
        order_id: "00000000-0000-4000-8000-00000000test",
        menu_item_id: "suppli",
        item_name_snapshot: "Suppli",
        item_price_snapshot: 3,
        ingredients_snapshot: null,
        quantity: 3,
        line_total: 9,
        notes: "senza sale",
        preparation_area_snapshot: "cucina",
        version: 1,
        category_name: "Antipasti e fritti",
        category_slug: "antipasti",
        category_sort_order: 0,
        extras: [],
      },
      {
        id: "test-ristorante",
        order_id: "00000000-0000-4000-8000-00000000test",
        menu_item_id: "carbonara",
        item_name_snapshot: "Carbonara",
        item_price_snapshot: 11,
        ingredients_snapshot: null,
        quantity: 1,
        line_total: 11,
        notes: "",
        preparation_area_snapshot: "cucina",
        version: 1,
        category_name: "Cucina",
        category_slug: "cucina",
        category_sort_order: 1,
        extras: [],
      },
      {
        id: "test-bevanda",
        order_id: "00000000-0000-4000-8000-00000000test",
        menu_item_id: "acqua",
        item_name_snapshot: "Acqua",
        item_price_snapshot: 2,
        ingredients_snapshot: null,
        quantity: 4,
        line_total: 8,
        notes: "",
        preparation_area_snapshot: "bar",
        version: 1,
        category_name: "Bevande",
        category_slug: "bevande",
        category_sort_order: 8,
        extras: [],
      },
    ],
  };
}
